# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern,
  - path_regex: \.(yaml|yml)$
    encrypted_regex: '^.*(?i)(foo)(?-i).*$'
    shamir_threshold: 2
    key_groups:
      - pgp:
          - BCE6E1D2A509156191BA016FDF0B5C535207EF1E
        # kms:
        #   - arn:
        #     role:
        #     context:
        #       foo:
        #   - arn:

      - pgp:
          - BCE6E1D2A509156191BA016FDF0B5C535207EF1E
        # kms:
        #   - arn:
        #   - arn:

      - pgp:
          - BCE6E1D2A509156191BA016FDF0B5C535207EF1E
        # kms:
        #   - arn:
        #   - arn:

  # - path_regex: \.(yaml|yml)$
    # encrypted_regex:
    # unencrypted_regex:
    # encrypted_suffix:
    # unencrypted_suffix:
  #   pgp: >-
  #     BCE6E1D2A509156191BA016FDF0B5C535207EF1E

  - path_regex: \.json$
    pgp: >-
      BCE6E1D2A509156191BA016FDF0B5C535207EF1E
    # kms:
    # hc_vault_uris:

  - path_regex: \.env$
    pgp: >-
      BCE6E1D2A509156191BA016FDF0B5C535207EF1E
    # gcp_kms:

  # Finally, if the rules above have not matched, this one is a
  # catchall that will encrypt the file using PGP
  # The absence of a path_regex means it will match everything
  - pgp: >-
      BCE6E1D2A509156191BA016FDF0B5C535207EF1E
  #   kms:
